meta_product_name: "Broomhill Cottages"
meta_title: "Broomhill Cottages - The Cleddau Estuary's Hidden Gem"
meta_description: "Beautiful Holiday Cottages, located in the heart of the Pembrokeshire Coast National Park"
meta_image: "outside_wall.jpg" # should exist in `app/assets/images/`
